INSERT INTO USERS (username, password, email, created_on) VALUES ('admin', '$2a$10$2dnbN.uDbYTGj2RRb2TAn.M4DWPpp0C5uo/2QUDOD5Hfl8Jx6wj6C', 'admin@email.com', CURRENT_TIMESTAMP());
INSERT INTO USERS (username, password, email, created_on) VALUES ('admin1', '$2a$10$2dnbN.uDbYTGj2RRb2TAn.M4DWPpp0C5uo/2QUDOD5Hfl8Jx6wj6C', 'admin1@email.com', CURRENT_TIMESTAMP());
INSERT INTO USERS (username, password, email, created_on) VALUES ('admin2', '$2a$10$2dnbN.uDbYTGj2RRb2TAn.M4DWPpp0C5uo/2QUDOD5Hfl8Jx6wj6C', 'admin2@email.com', CURRENT_TIMESTAMP());
INSERT INTO USERS (username, password, email, created_on) VALUES ('admin3', '$2a$10$2dnbN.uDbYTGj2RRb2TAn.M4DWPpp0C5uo/2QUDOD5Hfl8Jx6wj6C', 'admin3@email.com', CURRENT_TIMESTAMP());
INSERT INTO USERS (username, password, email, created_on) VALUES ('admin4', '$2a$10$2dnbN.uDbYTGj2RRb2TAn.M4DWPpp0C5uo/2QUDOD5Hfl8Jx6wj6C', 'admin4@email.com', CURRENT_TIMESTAMP());
INSERT INTO USERS (username, password, email, created_on) VALUES ('admin5', '$2a$10$2dnbN.uDbYTGj2RRb2TAn.M4DWPpp0C5uo/2QUDOD5Hfl8Jx6wj6C', 'admin5@email.com', CURRENT_TIMESTAMP());
INSERT INTO USERS (username, password, email, created_on) VALUES ('admin6', '$2a$10$2dnbN.uDbYTGj2RRb2TAn.M4DWPpp0C5uo/2QUDOD5Hfl8Jx6wj6C', 'admin6@email.com', CURRENT_TIMESTAMP());

INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 1', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 2', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 3', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 4', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 5', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 6', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 7', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 8', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 9', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 10', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 11', 5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 12', 5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 13', 5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 14', 6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO QUOTES (text, author_id, created_On, last_Updated_On) VALUES ('Quote number 15', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (1, 1, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (1, 2, -1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (1, 3, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (1, 4, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (2, 1, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (2, 2, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (2, 3, -1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (2, 4, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (2, 5, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (2, 6, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (2, 7, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (3, 1, -1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (3, 2, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (4, 1, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (4, 2, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (5, 1, -1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (6, 1, 1, CURRENT_TIMESTAMP());
INSERT INTO QUOTE_STATES (quote_id, user_id, vote_Value, voted_On) VALUES (7, 1, -1, CURRENT_TIMESTAMP());
